# Generated by Django 3.0.3 on 2020-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='description',
            new_name='flowerName',
        ),
        migrations.AddField(
            model_name='flower',
            name='caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flower',
            name='idImage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flower',
            name='img',
            field=models.ImageField(default='', upload_to='profile_image/'),
        ),
        migrations.AlterModelTable(
            name='flower',
            table='image',
        ),
    ]
