# Generated by Django 3.0.3 on 2020-02-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_auto_20200225_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='img',
        ),
    ]
