# Generated by Django 3.0.3 on 2020-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_remove_flower_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='idImage',
        ),
        migrations.AddField(
            model_name='flower',
            name='img',
            field=models.ImageField(default='', upload_to='profile_image/'),
        ),
    ]
